# Generated by Django 6.0 on 2026-02-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaklog',
            name='break_type',
            field=models.CharField(choices=[('tea', 'Tea Break'), ('lunch', 'Lunch Break')], default='tea', max_length=10),
            preserve_default=False,
        ),
    ]
