# Generated by Django 6.0 on 2026-03-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_breaklog_break_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('half-day', 'Half-Day'), ('absent', 'Absent')], default='present', max_length=20),
        ),
    ]
