# Generated by Django 5.0.1 on 2026-03-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_employeeprofile_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('half-day', 'Half-Day'), ('absent', 'Absent')], default='present', max_length=20),
        ),
    ]
