# Generated by Django 5.0.1 on 2026-03-25 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('check_in', 'Check In'), ('check_out', 'Check Out'), ('break_start', 'Break Start'), ('break_end', 'Break End'), ('leave_request', 'Leave Request'), ('leave_approve', 'Leave Approved'), ('leave_reject', 'Leave Rejected'), ('leave_cancel', 'Leave Cancelled'), ('profile_update', 'Profile Updated'), ('user_create', 'User Created'), ('user_delete', 'User Deleted'), ('overtime_start', 'Overtime Start'), ('overtime_end', 'Overtime End'), ('overtime_approve', 'Overtime Approved')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
