# Generated by Django 5.0.1 on 2026-03-26 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_options_overtime_hr_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='reason',
            field=models.TextField(blank=True, default='No reason provided'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
