# Generated by Django 5.0.1 on 2026-03-30 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_overtime_reason_overtime_requested_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('check_in', 'Check In'), ('check_out', 'Check Out'), ('break_start', 'Break Start'), ('break_end', 'Break End'), ('leave_request', 'Leave Request'), ('leave_approve', 'Leave Approved'), ('leave_reject', 'Leave Rejected'), ('leave_cancel', 'Leave Cancelled'), ('profile_update', 'Profile Updated'), ('user_create', 'User Created'), ('user_delete', 'User Deleted'), ('overtime_request', 'Overtime Requested'), ('overtime_start', 'Overtime Start'), ('overtime_end', 'Overtime End'), ('overtime_approve', 'Overtime Approved'), ('overtime_reject', 'Overtime Rejected'), ('wfh_request', 'WFH Requested'), ('wfh_approve', 'WFH Approved'), ('wfh_reject', 'WFH Rejected'), ('wfh_cancel', 'WFH Cancelled')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='WFHRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('hr_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hr_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wfh_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
