# Generated by Django 5.0.1 on 2026-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_auditlog_action_wfhrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('earned', 'Earned Leaves'), ('unpaid', 'Unpaid Leaves')], max_length=20),
        ),
    ]
