# Generated by Django 5.0.1 on 2026-04-02 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_employeemasterdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeemasterdata',
            new_name='attendance__employe_5d2f65_idx',
            old_name='attendance_e_employe_idx',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_change_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('hr', 'HR'), ('admin', 'Admin')], db_index=True, default='employee', max_length=20),
        ),
    ]
