# Generated by Django 5.0.1 on 2026-04-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_rename_attendance_e_employe_idx_attendance__employe_5d2f65_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('check_in', 'Check In'), ('check_out', 'Check Out'), ('break_start', 'Break Start'), ('break_end', 'Break End'), ('leave_request', 'Leave Request'), ('leave_approve', 'Leave Approved'), ('leave_reject', 'Leave Rejected'), ('leave_cancel', 'Leave Cancelled'), ('profile_update', 'Profile Updated'), ('user_create', 'User Created'), ('user_delete', 'User Deleted'), ('overtime_request', 'Overtime Requested'), ('overtime_start', 'Overtime Start'), ('overtime_end', 'Overtime End'), ('overtime_approve', 'Overtime Approved'), ('overtime_reject', 'Overtime Rejected'), ('wfh_request', 'WFH Requested'), ('wfh_approve', 'WFH Approved'), ('wfh_reject', 'WFH Rejected'), ('wfh_cancel', 'WFH Cancelled'), ('role_change', 'Role Changed'), ('attendance_status_change', 'Attendance Status Changed')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('hr', 'HR/Admin')], db_index=True, default='employee', max_length=20),
        ),
    ]
