# Generated by Django 5.0.1 on 2026-04-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_auditlog_action_alter_employeeprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('earned', 'Earned Leaves'), ('menstrual', 'Menstrual Leave'), ('unpaid', 'Unpaid Leaves')], max_length=20),
        ),
    ]
