# Generated by Django 5.0.1 on 2026-04-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_employeeprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='work_mode',
            field=models.CharField(choices=[('office', 'Office Only'), ('hybrid', 'Hybrid (Office + WFH)'), ('permanent_wfh', 'Permanent Work From Home')], default='office', help_text='Determines network access requirements for check-in', max_length=20),
        ),
    ]
