# Generated by Django 5.0.1 on 2026-04-22 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_add_work_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_override_enabled', models.BooleanField(default=False, help_text='When enabled, all employees can check-in from any location (bypasses IP restrictions)')),
                ('emergency_override_reason', models.TextField(blank=True, help_text="Reason for enabling emergency override (e.g., 'Regus network down')", null=True)),
                ('emergency_override_enabled_at', models.DateTimeField(blank=True, help_text='When the override was enabled', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('emergency_override_enabled_by', models.ForeignKey(blank=True, help_text='HR user who enabled the override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_overrides_enabled', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
