# Generated by Django 5.0.1 on 2026-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_company_holidays'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyholiday',
            name='unique_holiday_date_name',
        ),
        migrations.RemoveIndex(
            model_name='companyholiday',
            name='holiday_date_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='companyholiday',
            name='holiday_type_idx',
        ),
        migrations.RenameIndex(
            model_name='onsiterequest',
            new_name='attendance__employe_f4469a_idx',
            old_name='attendance_o_employe_idx',
        ),
        migrations.RenameIndex(
            model_name='onsiterequest',
            new_name='attendance__status_4fda25_idx',
            old_name='attendance_o_status_idx',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='office_ips',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed office IP addresses with metadata (JSON format)'),
        ),
    ]
