# Generated by Django 5.0.3 on 2026-08-07 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_request_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_team_leader',
            field=models.BooleanField(db_index=True, default=False, help_text='Automatically set to True when user is assigned as Team Leader of any team'),
        ),
        migrations.AddField(
            model_name='onsiterequest',
            name='tl_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_commented_onsite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onsiterequest',
            name='tl_comment',
            field=models.TextField(blank=True, help_text="Team Leader's comment", null=True),
        ),
        migrations.AddField(
            model_name='onsiterequest',
            name='tl_commented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtime',
            name='tl_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_commented_overtimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtime',
            name='tl_comment',
            field=models.TextField(blank=True, help_text="Team Leader's comment", null=True),
        ),
        migrations.AddField(
            model_name='overtime',
            name='tl_commented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique team name (e.g., "Frontend Team", "Marketing Team")', max_length=100, unique=True)),
                ('department', models.CharField(db_index=True, help_text='Department this team belongs to', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Team description, objectives, or notes', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this team is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='HR/Admin who created this team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
                ('team_leader', models.ForeignKey(blank=True, help_text='Team Leader responsible for this team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this membership is currently active')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, help_text='When this membership was deactivated', null=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='HR/Admin who added this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='The employee who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='The team this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='attendance.team')),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['department', 'is_active'], name='attendance__departm_b53898_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_leader', 'is_active'], name='attendance__team_le_555c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'employee', 'is_active'], name='attendance__team_id_40febe_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['employee', 'is_active'], name='attendance__employe_83fc86_idx'),
        ),
    ]
