# Generated by Django 5.0.3 on 2026-08-24 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_team_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly base salary', max_digits=10),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='esi_number',
            field=models.CharField(blank=True, help_text='Employee State Insurance Number', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='ot_rate',
            field=models.DecimalField(decimal_places=2, default=300.0, help_text='Overtime hourly rate', max_digits=8),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pf_number',
            field=models.CharField(blank=True, help_text='Provident Fund Number', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='uan_number',
            field=models.CharField(blank=True, help_text='Universal Account Number', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year (e.g., 2026)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('paid', 'Paid')], db_index=True, default='draft', max_length=20)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_overtime', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Base salary for the month', max_digits=10)),
                ('working_days', models.IntegerField(help_text='Total working days in the month (excluding weekends & holidays)')),
                ('per_day_salary', models.DecimalField(decimal_places=2, help_text='Calculated: base_salary / working_days', max_digits=10)),
                ('present_days', models.IntegerField(default=0, help_text='Full working days')),
                ('absent_days', models.IntegerField(default=0, help_text='Absent days')),
                ('half_days', models.IntegerField(default=0, help_text='Half day/late check-ins')),
                ('late_days', models.IntegerField(default=0, help_text='Late arrivals count (informational)')),
                ('wfh_days', models.IntegerField(default=0, help_text='Work from home days (counted as present)')),
                ('paid_leaves', models.IntegerField(default=0, help_text='Paid leave days taken (within 18 limit)')),
                ('unpaid_leaves', models.IntegerField(default=0, help_text='Unpaid leave days (beyond 18)')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Approved OT hours', max_digits=5)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=300.0, help_text='OT rate per hour', max_digits=8)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated: hours × rate', max_digits=10)),
                ('half_day_deduction', models.DecimalField(decimal_places=2, default=0.0, help_text='(per_day_salary / 2) × half_days', max_digits=10)),
                ('absent_deduction', models.DecimalField(decimal_places=2, default=0.0, help_text='per_day_salary × absent_days', max_digits=10)),
                ('unpaid_leave_deduction', models.DecimalField(decimal_places=2, default=0.0, help_text='per_day_salary × unpaid_leaves', max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Manual deductions', max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all deductions', max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='base_salary + overtime_amount', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='gross_salary - total_deductions + manual_adjustment', max_digits=10)),
                ('manual_adjustment', models.DecimalField(decimal_places=2, default=0.0, help_text='Manual bonus or deduction (+/-)', max_digits=10)),
                ('adjustment_reason', models.TextField(blank=True, help_text='Reason for manual adjustment')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('paid', 'Paid'), ('hold', 'On Hold')], db_index=True, default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID or reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='attendance.employeeprofile')),
                ('payroll_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.payrollcycle')),
            ],
            options={
                'ordering': ['employee__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Calendar year')),
                ('sick_leave_allocated', models.IntegerField(default=6)),
                ('sick_leave_used', models.IntegerField(default=0)),
                ('sick_leave_balance', models.IntegerField(default=6)),
                ('casual_leave_allocated', models.IntegerField(default=6)),
                ('casual_leave_used', models.IntegerField(default=0)),
                ('casual_leave_balance', models.IntegerField(default=6)),
                ('earned_leave_allocated', models.IntegerField(default=6)),
                ('earned_leave_used', models.IntegerField(default=0)),
                ('earned_leave_balance', models.IntegerField(default=6)),
                ('total_allocated', models.IntegerField(default=18)),
                ('total_used', models.IntegerField(default=0)),
                ('total_balance', models.IntegerField(default=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='attendance.employeeprofile')),
            ],
            options={
                'ordering': ['-year', 'employee__employee_id'],
                'indexes': [models.Index(fields=['year', 'employee'], name='attendance__year_bad831_idx')],
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='payrollcycle',
            index=models.Index(fields=['year', 'month'], name='attendance__year_7aef36_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcycle',
            index=models.Index(fields=['status'], name='attendance__status_3e7aae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollcycle',
            unique_together={('month', 'year')},
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['payroll_cycle', 'employee'], name='attendance__payroll_378b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['payment_status'], name='attendance__payment_62ae27_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['employee'], name='attendance__employe_4e9640_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollentry',
            unique_together={('payroll_cycle', 'employee')},
        ),
    ]
