# Generated by Django 5.0.3 on 2026-09-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_employeeprofile_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_start_time',
            field=models.TimeField(null=True, blank=True, help_text='Start time for half-day leave (e.g., 09:00)'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_end_time',
            field=models.TimeField(null=True, blank=True, help_text='End time for half-day leave (e.g., 13:00)'),
        ),
    ]
